# Generated by Django 3.2.8 on 2021-10-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStocks',
            fields=[
                ('symbol', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, max_length=20, null=True)),
                ('change', models.FloatField(blank=True, max_length=20, null=True)),
                ('change_percent', models.FloatField(blank=True, max_length=20, null=True)),
                ('prev_close_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('open_value', models.FloatField(blank=True, max_length=20, null=True)),
                ('days_range', models.CharField(blank=True, max_length=20, null=True)),
                ('fifty_two_week_range', models.CharField(blank=True, max_length=20, null=True)),
                ('volume', models.IntegerField(blank=True, max_length=20, null=True)),
                ('avg_volume', models.IntegerField(blank=True, max_length=20, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=20, null=True)),
                ('dividend', models.CharField(blank=True, max_length=20, null=True)),
                ('prev_dividend_date', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
