# Generated by Django 3.2.8 on 2021-10-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStocks',
            fields=[
                ('symbol', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.FloatField(blank=True, max_length=50, null=True)),
                ('change', models.FloatField(blank=True, max_length=50, null=True)),
                ('change_amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('change_percent', models.FloatField(blank=True, max_length=50, null=True)),
                ('prev_close_value', models.FloatField(blank=True, max_length=50, null=True)),
                ('open_value', models.FloatField(blank=True, max_length=50, null=True)),
                ('bid_value', models.FloatField(blank=True, max_length=50, null=True)),
                ('bid_quantity', models.FloatField(blank=True, max_length=50, null=True)),
                ('ask_value', models.FloatField(blank=True, max_length=50, null=True)),
                ('ask_quantity', models.FloatField(blank=True, max_length=50, null=True)),
                ('days_high', models.FloatField(blank=True, max_length=50, null=True)),
                ('days_low', models.FloatField(blank=True, max_length=50, null=True)),
                ('fifty_two_week_high', models.FloatField(blank=True, max_length=50, null=True)),
                ('fifty_two_week_low', models.FloatField(blank=True, max_length=50, null=True)),
                ('volume', models.FloatField(blank=True, max_length=50, null=True)),
                ('avg_volume', models.FloatField(blank=True, max_length=50, null=True)),
                ('market_cap', models.FloatField(blank=True, max_length=50, null=True)),
                ('market_cap_prefix', models.CharField(blank=True, max_length=1, null=True)),
                ('beta', models.FloatField(blank=True, max_length=50, null=True)),
                ('pe_ratio', models.FloatField(blank=True, max_length=50, null=True)),
                ('eps_ratio', models.FloatField(blank=True, max_length=50, null=True)),
                ('forward_dividend_yield', models.FloatField(blank=True, max_length=50, null=True)),
                ('forward_dividend_percentage', models.FloatField(blank=True, max_length=50, null=True)),
                ('prev_dividend_date', models.CharField(blank=True, max_length=50, null=True)),
                ('one_year_target', models.FloatField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
