# Generated by Django 3.2.8 on 2021-10-17 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livestocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestocks',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='livestocks',
            name='change_percent',
        ),
        migrations.RemoveField(
            model_name='livestocks',
            name='forward_dividend_percentage',
        ),
        migrations.RemoveField(
            model_name='livestocks',
            name='market_cap_prefix',
        ),
        migrations.RemoveField(
            model_name='livestocks',
            name='one_year_target',
        ),
        migrations.RemoveField(
            model_name='livestocks',
            name='prev_dividend_date',
        ),
    ]
