# Generated by Django 3.2.8 on 2021-10-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211020_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='portfolio_name',
            new_name='name',
        ),
    ]
