# Generated by Django 3.2.8 on 2021-10-20 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_portfolio_name_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorecords',
            name='symbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.livestocks'),
        ),
    ]
