# Generated by Django 3.2.8 on 2021-10-21 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211020_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliorecords',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='portfoliorecords',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliorecords',
            name='trade_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterModelTable(
            name='portfoliorecords',
            table='Portfolio Records',
        ),
    ]
