# Generated by Django 3.2.8 on 2021-10-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211022_0448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliorecords',
            options={'verbose_name_plural': 'Portfolio Records'},
        ),
        migrations.AlterModelTable(
            name='portfoliorecords',
            table=None,
        ),
    ]
