export const PORTFOLIO_CREATE_REQUEST = 'PORTFOLIO_CREATE_REQUEST'
export const PORTFOLIO_CREATE_SUCCESS = 'PORTFOLIO_CREATE_SUCCESS'
export const PORTFOLIO_CREATE_FAIL = 'PORTFOLIO_CREATE_FAIL'

export const PORTFOLIO_CREATE_RESET = 'PORTFOLIO_CREATE_RESET'

export const PORTFOLIO_REQUEST = 'PORTFOLIO_REQUEST'
export const PORTFOLIO_SUCCESS = 'PORTFOLIO_SUCCESS'
export const PORTFOLIO_FAIL = 'PORTFOLIO_FAIL'

export const PORTFOLIO_DELETE_REQUEST = 'PORTFOLIO_DELETE_REQUEST'
export const PORTFOLIO_DELETE_SUCCESS = 'PORTFOLIO_DELETE_SUCCESS'
export const PORTFOLIO_DELETE_FAIL = 'PORTFOLIO_DELETE_FAIL'

export const PORTFOLIO_DETAILS_REQUEST = 'PORTFOLIO_DETAILS_REQUEST'
export const PORTFOLIO_DETAILS_SUCCESS = 'PORTFOLIO_DETAILS_SUCCESS'
export const PORTFOLIO_DETAILS_FAIL = 'PORTFOLIO_DETAILS_FAIL'

export const PORTFOLIO_RECORD_CREATE_REQUEST = 'PORTFOLIO_RECORD_CREATE_REQUEST'
export const PORTFOLIO_RECORD_CREATE_SUCCESS = 'PORTFOLIO_RECORD_CREATE_SUCCESS'
export const PORTFOLIO_RECORD_CREATE_FAIL = 'PORTFOLIO_RECORD_CREATE_FAIL'

export const PORTFOLIO_RECORD_DELETE_REQUEST = 'PORTFOLIO_RECORD_DELETE_REQUEST'
export const PORTFOLIO_RECORD_DELETE_SUCCESS = 'PORTFOLIO_RECORD_DELETE_SUCCESS'
export const PORTFOLIO_RECORD_DELETE_FAIL = 'PORTFOLIO_RECORD_DELETE_FAIL'

export const PORTFOLIO_RECORD_UPDATE_REQUEST = 'PORTFOLIO_RECORD_UPDATE_REQUEST'
export const PORTFOLIO_RECORD_UPDATE_SUCCESS = 'PORTFOLIO_RECORD_UPDATE_SUCCESS'
export const PORTFOLIO_RECORD_UPDATE_FAIL = 'PORTFOLIO_RECORD_UPDATE_FAIL'