export const STOCKS_LIST_REQUEST = 'STOCKS_LIST_REQUEST'
export const STOCKS_LIST_SUCCESS = 'STOCKS_LIST_SUCCESS'
export const STOCKS_LIST_FAIL = 'STOCKS_LIST_FAIL'

export const STOCKS_DETAILS_REQUEST = 'STOCKS_DETAILS_REQUEST'
export const STOCKS_DETAILS_SUCCESS = 'STOCKS_DETAILS_SUCCESS'
export const STOCKS_DETAILS_FAIL = 'STOCKS_DETAILS_FAIL'

export const STOCKS_TOP_GAINER_REQUEST = 'STOCKS_TOP_GAINER_REQUEST'
export const STOCKS_TOP_GAINER_SUCCESS = 'STOCKS_TOP_GAINER_SUCCESS'
export const STOCKS_TOP_GAINER_FAIL = 'STOCKS_TOP_GAINER_FAIL'

export const STOCKS_TOP_LOSER_REQUEST = 'STOCKS_TOP_LOSER_REQUEST'
export const STOCKS_TOP_LOSER_SUCCESS = 'STOCKS_TOP_LOSER_SUCCESS'
export const STOCKS_TOP_LOSER_FAIL = 'STOCKS_TOP_LOSER_FAIL'